Update docker-compose-training-data.yaml
Added service to load data from block storage to object store

diff --git a/docker/docker-compose-training-data.yaml b/docker/docker-compose-training-data.yaml
--- a/docker/docker-compose-training-data.yaml
+++ b/docker/docker-compose-training-data.yaml
@@ -2,6 +2,33 @@ name: fashion-extraction
 volumes:
   block-persist-project15:
 services:
+  load-data:
+    container_name: etl_load_data
+    image: rclone/rclone:latest
+    volumes:
+      - /mnt/block:/mnt/openvid
+      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
+    entrypoint: /bin/sh
+    command:
+      - -c
+      - |
+        if [ -z "$RCLONE_CONTAINER" ]; then
+          echo "ERROR: RCLONE_CONTAINER is not set"
+          exit 1
+        fi
+        echo "Cleaning up existing contents of container..."
+        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
+
+        rclone copy /mnt/openvid/only_fashion_show_dataset:$RCLONE_CONTAINER \
+        --progress \
+        --transfers=32 \
+        --checkers=16 \
+        --multi-thread-streams=4 \
+        --fast-list
+
+        echo "Listing directories in container after load stage:"
+        rclone lsd chi_tacc:$RCLONE_CONTAINER
+        
   extract-fashion-videos:
     container_name: fashion_extraction
     image: python:3.11
